import { Express } from "express";
import RoutesController from "./routesController/RoutesController";
class Routes {
  private routesController: RoutesController;
  private routeparent: string;
  constructor(routeparent: string, app: Express) {
    this.routesController = new RoutesController();
    this.routeparent = routeparent;
    this.configureRoutes(app);
  }
  private configureRoutes(app: Express) {
    //-------CATEGORIAS--//
    app
      .route(`${this.routeparent}/categoria`)
      .post(this.routesController.createCategoria);
    app
      .route(`${this.routeparent}/categoria`)
      .get(this.routesController.getCategorias);
    app
      .route(`${this.routeparent}/categoria/:id`)
      .get(this.routesController.getCategoria);
    app
      .route(`${this.routeparent}/categoriaCod/:codigo`)
      .get(this.routesController.getCategoriaCod);
    app
      .route(`${this.routeparent}/categoria/:id`)
      .put(this.routesController.updateCategoria);
    app
      .route(`${this.routeparent}/categoria/:id`)
      .delete(this.routesController.removeCategoria);
    app
      .route(`${this.routeparent}/searchCat/:search`)
      .get(this.routesController.searchCat);
    //-------SUB-CATEGORIAS--//
    app
      .route(`${this.routeparent}/subCategoria`)
      .post(this.routesController.createSubCategoria);
    app
      .route(`${this.routeparent}/subCategoria`)
      .get(this.routesController.getSubCategorias);
    app
      .route(`${this.routeparent}/subCategoria/:id`)
      .get(this.routesController.getSubCategoria);
    app
      .route(`${this.routeparent}/subCategoriaCod/:codigo`)
      .get(this.routesController.getSubCategoriaCod);
    app
      .route(`${this.routeparent}/subCategoria/:id`)
      .put(this.routesController.updateSubCategoria);
    app
      .route(`${this.routeparent}/subCategoria/:id`)
      .delete(this.routesController.removeSubCategoria);
    app
      .route(`${this.routeparent}/searchSubCat/:search`)
      .get(this.routesController.searchSubCategoria);
    //-------PROVEEDORES--//
    app
      .route(`${this.routeparent}/proveedor`)
      .post(this.routesController.createProveedores);
    app
      .route(`${this.routeparent}/proveedores`)
      .get(this.routesController.getProveedoress);
    app
      .route(`${this.routeparent}/proveedor/:id`)
      .get(this.routesController.getProveedores);
    app
      .route(`${this.routeparent}/proveedorCod/:codigo`)
      .get(this.routesController.getProveedoresCod);
    app
      .route(`${this.routeparent}/proveedor/:id`)
      .put(this.routesController.updateProveedores);
    app
      .route(`${this.routeparent}/proveedor/:id`)
      .delete(this.routesController.removeProveedores);
    app
      .route(`${this.routeparent}/searchProveedor/:search`)
      .get(this.routesController.searchProveedor);
    //-------PROGRAMA--//
    app
      .route(`${this.routeparent}/programa`)
      .post(this.routesController.createPrograma);
    app
      .route(`${this.routeparent}/programas`)
      .get(this.routesController.getProgramas);
    app
      .route(`${this.routeparent}/programa/:id`)
      .get(this.routesController.getPrograma);
    app
      .route(`${this.routeparent}/programaCod/:codigo`)
      .get(this.routesController.getProgramaCod);
    app
      .route(`${this.routeparent}/programa/:id`)
      .put(this.routesController.updatePrograma);
    app
      .route(`${this.routeparent}/programa/:id`)
      .delete(this.routesController.removePrograma);
    app
      .route(`${this.routeparent}/searchProg/:search`)
      .get(this.routesController.searchProg);
    //-------PROYECTO--//
    app
      .route(`${this.routeparent}/proyecto`)
      .post(this.routesController.createProyecto);
    app
      .route(`${this.routeparent}/proyectos`)
      .get(this.routesController.getProyectos);
    app
      .route(`${this.routeparent}/proyecto/:id`)
      .get(this.routesController.getProyecto);
    app
      .route(`${this.routeparent}/proyectoCod/:codigo`)
      .get(this.routesController.getProyectoCod);
    app
      .route(`${this.routeparent}/proyecto/:id`)
      .put(this.routesController.updateProyecto);
    app
      .route(`${this.routeparent}/proyecto/:id`)
      .delete(this.routesController.removeProyecto);
    app
      .route(`${this.routeparent}/searchProy/:search`)
      .get(this.routesController.searchProy);
    //-------ACTIVIDAD--//
    app
      .route(`${this.routeparent}/actividad`)
      .post(this.routesController.createActividad);
    app
      .route(`${this.routeparent}/actividades`)
      .get(this.routesController.getActividades);
    app
      .route(`${this.routeparent}/actividad/:id`)
      .get(this.routesController.getActividad);
    app
      .route(`${this.routeparent}/actividadCod/:codigo`)
      .get(this.routesController.getActividadCod);
    app
      .route(`${this.routeparent}/actividad/:id`)
      .put(this.routesController.updateActividad);
    app
      .route(`${this.routeparent}/actividad/:id`)
      .delete(this.routesController.removeActividad);
    app
      .route(`${this.routeparent}/searchActividad/:search`)
      .get(this.routesController.searchActividad);
    //--------------CSV--------------//
    app
      .route(`${this.routeparent}/csv`)
      .post(this.routesController.uploadCsvPoa);
    app
      .route(`${this.routeparent}/segPoas`)
      .get(this.routesController.readSegPoa);
    app
      .route(`${this.routeparent}/catProg`)
      .get(this.routesController.getCatProg);
    app
      .route(`${this.routeparent}/searchSegPoa/:search`)
      .get(this.routesController.searchSegPoa);
    //-------ARTICULOS--//
    app
      .route(`${this.routeparent}/articulo`)
      .post(this.routesController.createArticulo);
    app
      .route(`${this.routeparent}/articulos`)
      .get(this.routesController.getArticulos);
    app
      .route(`${this.routeparent}/articulo/:id`)
      .get(this.routesController.getArticulo);
    app
      .route(`${this.routeparent}/articuloCod/:codigo`)
      .get(this.routesController.getArticuloCod);
    app
      .route(`${this.routeparent}/articulo/:id`)
      .put(this.routesController.updateArticulo);
    app
      .route(`${this.routeparent}/articulo/:id`)
      .delete(this.routesController.removeArticulo);
    app
      .route(`${this.routeparent}/searchArticulo/:search`)
      .get(this.routesController.searchArticulo);
    //-------MEDIDAS--//
    app
      .route(`${this.routeparent}/medida`)
      .post(this.routesController.createMedida);
    app
      .route(`${this.routeparent}/medidas`)
      .get(this.routesController.getMedidas);
    app
      .route(`${this.routeparent}/medida/:id`)
      .get(this.routesController.getMedida);
    app
      .route(`${this.routeparent}/medida/:id`)
      .put(this.routesController.updateMedida);
    app
      .route(`${this.routeparent}/medida/:id`)
      .delete(this.routesController.removeMedida);
    app
      .route(`${this.routeparent}/searchmedida/:search`)
      .get(this.routesController.searchMedida);
    //-------INGRESOS--//
    app
      .route(`${this.routeparent}/ingreso`)
      .post(this.routesController.createIngreso);
    app
      .route(`${this.routeparent}/ingresos`)
      .get(this.routesController.getIngresos);
    app
      .route(`${this.routeparent}/ingreso/:id`)
      .get(this.routesController.getIngreso);
    app
      .route(`${this.routeparent}/ingreso/:id`)
      .put(this.routesController.updateIngreso);
    app
      .route(`${this.routeparent}/ingreso/:id`)
      .delete(this.routesController.removeIngreso);
    app
      .route(`${this.routeparent}/searchingreso/:search`)
      .get(this.routesController.searchIngreso);
  }
}
export default Routes;
